from dataclasses import dataclass


@dataclass(frozen=True)
class BrandAlias:
    canonical: str
    aliases: tuple[str, ...]
    category_hint: str | None = None


BRAND_ALIASES: tuple[BrandAlias, ...] = (
    # Abarrotes
    BrandAlias("Costeño", ("costeno", "costeño"), "abarrotes"),
    BrandAlias("Don Vittorio", ("don vittorio", "vittorio"), "abarrotes"),
    BrandAlias("Primor", ("primor",), "abarrotes"),
    BrandAlias("Florida", ("florida",), "abarrotes"),
    BrandAlias("Bell's", ("bell's", "bells", "bell s"), "abarrotes"),
    BrandAlias("3 Ositos", ("3 ositos", "tres ositos"), "abarrotes"),
    BrandAlias("Cocinero", ("cocinero",), "abarrotes"),
    BrandAlias("Capri", ("capri",), "abarrotes"),
    BrandAlias("Crisol", ("crisol",), "abarrotes"),
    BrandAlias("Sao", ("sao aceite", "aceite sao"), "abarrotes"),
    BrandAlias("Alacena", ("alacena",), "abarrotes"),
    BrandAlias("Hellmann's", ("hellmanns", "hellmann's"), "abarrotes"),
    BrandAlias("Maggi", ("maggi",), "abarrotes"),
    BrandAlias("Knorr", ("knorr",), "abarrotes"),
    BrandAlias("Ajinomoto", ("ajinomoto", "aji-no-moto", "aji no moto"), "abarrotes"),
    BrandAlias("Sibarita", ("sibarita",), "abarrotes"),
    BrandAlias("Negrita", ("negrita",), "abarrotes"),
    BrandAlias("Quaker", ("quaker",), "abarrotes"),
    BrandAlias("Ángel", ("angel cereal", "cereal angel", "angel avena", "avena angel"), "abarrotes"),
    BrandAlias("Fanny", ("fanny",), "abarrotes"),
    BrandAlias("Real", ("real conserva", "conserva real"), "abarrotes"),
    BrandAlias("Campomar", ("campomar",), "abarrotes"),
    BrandAlias("A-1", ("a-1 atun", "a1 atun", "a-1 atún"), "abarrotes"),
    BrandAlias("Maizena", ("maizena",), "abarrotes"),
    BrandAlias("Nestlé", ("nestle", "nestlé", "nestla"), "abarrotes"),
    BrandAlias("La Iberica", ("la iberica", "iberica chocolate"), "abarrotes"),

    # Lácteos
    BrandAlias("Gloria", ("gloria",), "lacteos"),
    BrandAlias("Laive", ("laive",), "lacteos"),
    BrandAlias("Pura Vida", ("pura vida",), "lacteos"),
    BrandAlias("Bonlé", ("bonle", "bonlé"), "lacteos"),
    BrandAlias("Bella Holandesa", ("bella holandesa",), "lacteos"),
    BrandAlias("Yoplait", ("yoplait",), "lacteos"),
    BrandAlias("Milkito", ("milkito",), "lacteos"),
    BrandAlias("Vigor", ("vigor lacteo", "vigor leche"), "lacteos"),

    # Bebidas
    BrandAlias("Inca Kola", ("inca kola", "incakola"), "bebidas"),
    BrandAlias("Coca-Cola", ("coca cola", "coca-cola", "cocacola"), "bebidas"),
    BrandAlias("Fanta", ("fanta",), "bebidas"),
    BrandAlias("Sprite", ("sprite",), "bebidas"),
    BrandAlias("Pepsi", ("pepsi",), "bebidas"),
    BrandAlias("Seven Up", ("7up", "seven up", "7 up"), "bebidas"),
    BrandAlias("Guaraná", ("guarana", "guaraná"), "bebidas"),
    BrandAlias("Kola Real", ("kola real", "kr cola"), "bebidas"),
    BrandAlias("Big Cola", ("big cola",), "bebidas"),
    BrandAlias("San Luis", ("san luis",), "bebidas"),
    BrandAlias("Cielo", ("cielo agua", "agua cielo"), "bebidas"),
    BrandAlias("San Mateo", ("san mateo",), "bebidas"),
    BrandAlias("San Carlos", ("san carlos agua", "agua san carlos"), "bebidas"),
    BrandAlias("Cifrut", ("cifrut",), "bebidas"),
    BrandAlias("Sporade", ("sporade",), "bebidas"),
    BrandAlias("Pulp", ("pulp",), "bebidas"),
    BrandAlias("Frugos", ("frugos", "frugos del valle"), "bebidas"),
    BrandAlias("Tampico", ("tampico",), "bebidas"),
    BrandAlias("Aquarius", ("aquarius",), "bebidas"),
    BrandAlias("Powerade", ("powerade",), "bebidas"),
    BrandAlias("Gatorade", ("gatorade",), "bebidas"),
    BrandAlias("Volt", ("volt energy", "volt energizante", "energizante volt"), "bebidas"),
    BrandAlias("Maltin Power", ("maltin power", "maltin"), "bebidas"),
    BrandAlias("Red Bull", ("red bull", "redbull"), "bebidas"),
    BrandAlias("Monster", ("monster energy",), "bebidas"),
    BrandAlias("Pisco", ("pisco quebranta", "pisco italia", "pisco acholado", "pisco torontel"), "bebidas"),
    BrandAlias("Cuatro Gallos", ("cuatro gallos",), "bebidas"),
    BrandAlias("Tres Generaciones", ("tres generaciones",), "bebidas"),

    # Snacks y golosinas
    BrandAlias("Field", ("field",), "snacks y golosinas"),
    BrandAlias("Sublime", ("sublime",), "snacks y golosinas"),
    BrandAlias("Triángulo", ("triangulo", "triángulo"), "snacks y golosinas"),
    BrandAlias("Casino", ("casino",), "snacks y golosinas"),
    BrandAlias("Oreo", ("oreo",), "snacks y golosinas"),
    BrandAlias("Chizitos", ("chizitos",), "snacks y golosinas"),
    BrandAlias("Lay's", ("lays", "lay's"), "snacks y golosinas"),
    BrandAlias("Cuates", ("cuates",), "snacks y golosinas"),
    BrandAlias("Costa", ("costa",), "snacks y golosinas"),
    BrandAlias("Picaras", ("picaras",), "snacks y golosinas"),
    BrandAlias("Cua Cua", ("cua cua", "cuacua"), "snacks y golosinas"),
    BrandAlias("Soda Field", ("soda field", "soda v"), "snacks y golosinas"),
    BrandAlias("Margaritas", ("margaritas galleta", "galleta margarita"), "snacks y golosinas"),
    BrandAlias("Glacitas", ("glacitas",), "snacks y golosinas"),
    BrandAlias("Charada", ("charada galleta",), "snacks y golosinas"),
    BrandAlias("Vainilla Field", ("vainilla field",), "snacks y golosinas"),
    BrandAlias("Animalitos", ("animalitos galleta", "galleta animalitos"), "snacks y golosinas"),
    BrandAlias("Doña Pepa", ("dona pepa", "doña pepa"), "snacks y golosinas"),
    BrandAlias("Tentación", ("tentacion galleta", "galleta tentacion"), "snacks y golosinas"),
    BrandAlias("Doritos", ("doritos",), "snacks y golosinas"),
    BrandAlias("Cheese Tris", ("cheese tris",), "snacks y golosinas"),
    BrandAlias("Piqueo Snax", ("piqueo snax",), "snacks y golosinas"),
    BrandAlias("Karinto", ("karinto",), "snacks y golosinas"),
    BrandAlias("Pringles", ("pringles",), "snacks y golosinas"),
    BrandAlias("Tortees", ("tortees",), "snacks y golosinas"),
    BrandAlias("Ritz", ("ritz", "galleta ritz", "ritz crackers"), "snacks y golosinas"),
    BrandAlias("Princesa", ("princesa chocolate", "chocolate princesa"), "snacks y golosinas"),
    BrandAlias("Doña Pepa Nik", ("nik chocolate",), "snacks y golosinas"),

    # Limpieza
    BrandAlias("Bolívar", ("bolivar", "bolívar"), "limpieza"),
    BrandAlias("Ariel", ("ariel",), "limpieza"),
    BrandAlias("Sapolio", ("sapolio",), "limpieza"),
    BrandAlias("Ayudín", ("ayudin", "ayudín"), "limpieza"),
    BrandAlias("Opal", ("opal",), "limpieza"),
    BrandAlias("Marsella", ("marsella",), "limpieza"),
    BrandAlias("Ace", ("ace detergente", "detergente ace"), "limpieza"),
    BrandAlias("Skip", ("skip detergente", "detergente skip"), "limpieza"),
    BrandAlias("Magistral", ("magistral",), "limpieza"),
    BrandAlias("Vel Rosita", ("vel rosita",), "limpieza"),
    BrandAlias("Patito", ("patito lavavajilla", "patito jabon"), "limpieza"),
    BrandAlias("Magia Blanca", ("magia blanca",), "limpieza"),
    BrandAlias("Poett", ("poett",), "limpieza"),
    BrandAlias("Mr. Músculo", ("mr musculo", "mr. musculo", "mr. músculo", "mr músculo"), "limpieza"),
    BrandAlias("Fabuloso", ("fabuloso",), "limpieza"),
    BrandAlias("Lysol", ("lysol",), "limpieza"),
    BrandAlias("Domestos", ("domestos",), "limpieza"),
    BrandAlias("Clorox", ("clorox",), "limpieza"),
    BrandAlias("Sapolio Cera", ("cera sapolio",), "limpieza"),
    BrandAlias("Glade", ("glade",), "limpieza"),

    # Cuidado personal
    BrandAlias("Head & Shoulders", ("head shoulders", "head & shoulders", "h&s"), "cuidado personal"),
    BrandAlias("Nivea", ("nivea", "niivea"), "cuidado personal"),
    BrandAlias("Portugal", ("portugal",), "cuidado personal"),
    BrandAlias("Pantene", ("pantene",), "cuidado personal"),
    BrandAlias("Sedal", ("sedal",), "cuidado personal"),
    BrandAlias("Dove", ("dove",), "cuidado personal"),
    BrandAlias("Pond's", ("ponds", "pond's", "pond"), "cuidado personal"),
    BrandAlias("Asepxia", ("asepxia",), "cuidado personal"),
    BrandAlias("Bioderma", ("bioderma", "bioderman"), "cuidado personal"),
    BrandAlias("Eucerin", ("eucerin",), "cuidado personal"),
    BrandAlias("Savital", ("savital", "sav anticaspa", "sav antica"), "cuidado personal"),
    BrandAlias("Plusbelle", ("plusbelle",), "cuidado personal"),
    BrandAlias("Konzil", ("konzil",), "cuidado personal"),
    BrandAlias("Klorane", ("klorane",), "cuidado personal"),
    BrandAlias("Kolynos", ("kolynos",), "cuidado personal"),
    BrandAlias("Dento", ("dento",), "cuidado personal"),
    BrandAlias("Colgate", ("colgate",), "cuidado personal"),
    BrandAlias("Oral-B", ("oral b", "oral-b"), "cuidado personal"),
    BrandAlias("Sensodyne", ("sensodyne",), "cuidado personal"),
    BrandAlias("Listerine", ("listerine",), "cuidado personal"),
    BrandAlias("Rexona", ("rexona",), "cuidado personal"),
    BrandAlias("Old Spice", ("old spice",), "cuidado personal"),
    BrandAlias("Speed Stick", ("speed stick",), "cuidado personal"),
    BrandAlias("Axe", ("axe desodorante", "desodorante axe"), "cuidado personal"),
    BrandAlias("Adidas", ("adidas desodorante", "desodorante adidas"), "cuidado personal"),
    BrandAlias("Dolce Vita", ("dolce vita",), "cuidado personal"),
    BrandAlias("Bonté", ("bonte", "bonté"), "cuidado personal"),
    BrandAlias("Heno de Pravia", ("heno de pravia", "heno pravia"), "cuidado personal"),
    BrandAlias("Johnson's", ("johnsons", "johnson's", "johnson", "jhonson", "jhon baby"), "bebés y mamá"),
    BrandAlias("Mustela", ("mustela",), "bebés y mamá"),
    BrandAlias("Babysec", ("babysec", "baby sec"), "bebés y mamá"),
    BrandAlias("Huggies", ("huggies", "huggees"), "bebés y mamá"),
    BrandAlias("Pampers", ("pampers",), "bebés y mamá"),
    BrandAlias("Bebito", ("bebito panal", "panal bebito"), "bebés y mamá"),
    BrandAlias("Always", ("always",), "cuidado personal"),
    BrandAlias("Kotex", ("kotex",), "cuidado personal"),
    BrandAlias("Nosotras", ("nosotras toalla", "toalla nosotras"), "cuidado personal"),
    BrandAlias("Stayfree", ("stayfree",), "cuidado personal"),
    BrandAlias("Ladysoft", ("ladysoft", "lady soft"), "cuidado personal"),
    BrandAlias("Elite", ("elite papel", "papel elite", "papel higienico elite"), "cuidado personal"),
    BrandAlias("Suave", ("suave papel", "papel suave"), "cuidado personal"),
    BrandAlias("Noble", ("noble papel", "papel noble"), "cuidado personal"),
    BrandAlias("Paracas", ("paracas papel", "papel paracas"), "cuidado personal"),
    BrandAlias("Scott", ("scott papel", "papel scott", "scott toalla"), "cuidado personal"),
    BrandAlias("Familia", ("familia papel", "papel familia"), "cuidado personal"),

    # Farmacia / OTC
    BrandAlias("Panadol", ("panadol",), "farmacia/otc"),
    BrandAlias("Mentholatum", ("mentholatum",), "farmacia/otc"),
    BrandAlias("Vick", ("vick", "vicks", "vaporub"), "farmacia/otc"),
    BrandAlias("Aspirina", ("aspirina", "aspirin"), "farmacia/otc"),
    BrandAlias("Apronax", ("apronax",), "farmacia/otc"),
    BrandAlias("Buscapina", ("buscapina",), "farmacia/otc"),
    BrandAlias("Mejoral", ("mejoral",), "farmacia/otc"),
    BrandAlias("Refrianex", ("refrianex",), "farmacia/otc"),
    BrandAlias("Notuss", ("notuss",), "farmacia/otc"),
    BrandAlias("Sertal", ("sertal",), "farmacia/otc"),
    BrandAlias("Doloflam", ("doloflam",), "farmacia/otc"),
    BrandAlias("Dolofrix", ("dolofrix",), "farmacia/otc"),
    BrandAlias("Pepto-Bismol", ("pepto bismol", "pepto-bismol", "pepto"), "farmacia/otc"),
    BrandAlias("Alka-Seltzer", ("alka seltzer", "alka-seltzer"), "farmacia/otc"),
    BrandAlias("Sal de Andrews", ("sal de andrews", "sal andrews"), "farmacia/otc"),
    BrandAlias("Eno", ("sal eno", "eno antiacido"), "farmacia/otc"),
    BrandAlias("Centrum", ("centrum",), "farmacia/otc"),
    BrandAlias("Redoxon", ("redoxon",), "farmacia/otc"),
    BrandAlias("Pharmaton", ("pharmaton",), "farmacia/otc"),
    BrandAlias("Supradyn", ("supradyn",), "farmacia/otc"),
    BrandAlias("Cicatricure", ("cicatricure",), "farmacia/otc"),
    BrandAlias("Bepanthene", ("bepanthene", "bepanten"), "farmacia/otc"),
    BrandAlias("Hipoglós", ("hipoglos", "hipoglós"), "farmacia/otc"),
    BrandAlias("Curitas", ("curitas", "curita"), "farmacia/otc"),
    BrandAlias("Bayer", ("bayer",), "farmacia/otc"),
    BrandAlias("Genfar", ("genfar",), "farmacia/otc"),
    BrandAlias("Hersil", ("hersil",), "farmacia/otc"),
    BrandAlias("Medifarma", ("medifarma",), "farmacia/otc"),
    BrandAlias("Sunvit", ("sunvit",), "farmacia/otc"),
    BrandAlias("Repel", ("repel repelente", "repelente repel"), "farmacia/otc"),
    BrandAlias("OFF!", ("off repelente", "repelente off"), "farmacia/otc"),
    BrandAlias("Himalaya", ("himalaya",), "farmacia/otc"),
    BrandAlias("Ashwagandha", ("ashwagandha", "ashwaganda"), "farmacia/otc"),
)


CATEGORY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "abarrotes": (
        "arroz",
        "azucar",
        "azúcar",
        "fideo",
        "fideos",
        "aceite",
        "atun",
        "atún",
        "avena",
        "harina",
        "menestra",
        "lenteja",
        "lentejas",
        "frijol",
        "frijoles",
        "arveja",
        "arvejas",
        "garbanzo",
        "quinua",
        "quinoa",
        "kiwicha",
        "mani",
        "maní",
        "soya",
        "cocoa",
        "mantequilla",
        "margarina",
        "mayonesa",
        "ketchup",
        "mostaza",
        "vinagre",
        "salsa",
        "sazonador",
        "consome",
        "consomé",
        "caldo",
    ),
    "bebidas": (
        "gaseosa",
        "agua",
        "bebida",
        "jugo",
        "nectar",
        "néctar",
        "rehidratante",
        "energizante",
        "cola",
        "kola",
        "orange",
        "naranja",
        "limon",
        "limón",
        "pisco",
        "cerveza",
        "vino",
    ),
    "snacks y golosinas": (
        "galleta",
        "galletas",
        "chocolate",
        "wafer",
        "snack",
        "papas",
        "maiz",
        "maíz",
        "chizito",
        "caramelo",
        "chupete",
        "gomitas",
        "toffee",
        "manjar",
    ),
    "limpieza": (
        "detergente",
        "lejia",
        "lejía",
        "lavavajilla",
        "limpiador",
        "desinfectante",
        "jabon",
        "jabón",
        "cera",
        "ambientador",
        "quitamanchas",
        "suavizante",
        "esponja",
    ),
    "cuidado personal": (
        "shampoo",
        "champu",
        "champú",
        "acondicionador",
        "pasta dental",
        "crema dental",
        "cepillo",
        "desodorante",
        "antitranspirante",
        "jabon tocador",
        "jabón tocador",
        "papel higienico",
        "papel higiénico",
        "toalla higienica",
        "toalla higiénica",
        "protector diario",
        "bloqueador",
        "protector solar",
        "afeitar",
    ),
    "bebés y mamá": (
        "panal",
        "pañal",
        "panales",
        "pañales",
        "toallita",
        "toallitas",
        "biberon",
        "biberón",
        "chupón",
        "chupon",
        "babero",
        "leche maternizada",
        "formula infantil",
        "fórmula infantil",
    ),
    "farmacia/otc": (
        "tableta",
        "tabletas",
        "capsula",
        "cápsula",
        "pastilla",
        "pastillas",
        "alcohol",
        "agua oxigenada",
        "unguento",
        "ungüento",
        "jarabe",
        "antigripal",
        "antialergico",
        "antialérgico",
        "analgesico",
        "analgésico",
        "ibuprofeno",
        "paracetamol",
        "naproxeno",
        "diclofenaco",
        "amoxicilina",
        "loratadina",
        "omeprazol",
        "metformina",
        "clopidogrel",
        "simeticona",
        "sulfato ferroso",
        "vitamina",
        "multivitaminico",
        "multivitamínico",
        "suplemento",
        "repelente",
        "antimosquito",
    ),
}


VARIANT_ALIASES: dict[str, tuple[str, ...]] = {
    "Naranja": ("naranja", "orange"),
    "Limón": ("limon", "limón", "lemon"),
    "Manzana": ("manzana", "apple"),
    "Fresa": ("fresa", "strawberry"),
    "Uva": ("uva", "grape"),
    "Piña": ("pina", "piña", "pineapple"),
    "Mango": ("mango",),
    "Durazno": ("durazno", "peach"),
    "Cola": ("cola",),
    "Mentol": ("mentol", "menthol"),
    "Eucalipto": ("eucalipto",),
    "Coco Fresh": ("coco fresh", "cocofresh"),
    "Coco": ("coco", "coconut"),
    "Milk Nutritiva": ("milk nutritiva", "nutritiva"),
    "Vainilla": ("vainilla", "vanilla"),
    "Chocolate": ("chocolate",),
    "Bebé": ("bebe", "bebé", "baby"),
    "Sensible": ("sensible", "sensitive", "piel sensible"),
    "Anticaspa": ("anticaspa", "anti caspa", "anti-caspa"),
    "Repara": ("repara", "reparacion", "reparación"),
    "Hidrata": ("hidrata", "hidratante"),
    "Sun": ("sun", "solar", "protector solar"),
    "Super Blanco": ("super blanco", "superblanco"),
    "Verde": ("verde",),
    "Morado": ("morado", "violeta"),
    "Floral": ("floral",),
    "Original": ("original", "clasico", "clásico"),
    "Leche Evaporada": ("leche evaporada", "evaporada"),
    "Leche Entera": ("leche entera", "entera"),
    "Sin Azúcar": ("sin azucar", "sin azúcar", "zero"),
    "Light": ("light", "lite"),
    "Blanca": ("blanca", "blanco"),
}


PRODUCT_TYPE_ALIASES: dict[str, tuple[str, ...]] = {
    "Gaseosa": ("gaseosa", "bebida gasificada", "soda"),
    "Agua": ("agua mineral", "agua de mesa", "agua sin gas", "agua con gas"),
    "Jugo": ("jugo", "nectar", "néctar", "refresco"),
    "Bebida rehidratante": ("rehidratante", "bebida rehidratante", "hidratante deportiva"),
    "Energizante": ("energizante", "bebida energetica", "bebida energética"),
    "Pisco": ("pisco",),
    "Cerveza": ("cerveza", "lager", "pilsner"),
    "Leche": ("leche evaporada", "leche entera", "leche descremada", "leche uht"),
    "Yogurt": ("yogurt", "yogur"),
    "Mantequilla": ("mantequilla",),
    "Margarina": ("margarina",),
    "Queso": ("queso",),
    "Arroz": ("arroz",),
    "Azúcar": ("azucar", "azúcar"),
    "Fideos": ("fideo", "fideos", "pasta", "tallarin", "tallarín", "spaghetti"),
    "Aceite": ("aceite",),
    "Atún": ("atun", "atún"),
    "Avena": ("avena",),
    "Quinua": ("quinua", "quinoa", "wuinoa"),
    "Kiwicha": ("kiwicha",),
    "Lentejas": ("lenteja", "lentejas"),
    "Frijoles": ("frijol", "frijoles", "porotos"),
    "Maní": ("mani", "maní", "cacahuate"),
    "Soya": ("soya", "soja"),
    "Mayonesa": ("mayonesa",),
    "Ketchup": ("ketchup",),
    "Mostaza": ("mostaza",),
    "Galleta": ("galleta", "galletas"),
    "Chocolate": ("chocolate",),
    "Caramelo": ("caramelo", "caramelos"),
    "Snack": ("snack", "papas", "chizito", "maiz", "maíz", "chips"),
    "Detergente": ("detergente",),
    "Lejía": ("lejia", "lejía"),
    "Lavavajilla": ("lavavajilla",),
    "Jabón": ("jabon", "jabón"),
    "Cera": ("cera para piso", "cera multiusos", "abrillantador"),
    "Ambientador": ("ambientador",),
    "Shampoo": ("shampoo", "champu", "champú"),
    "Acondicionador": ("acondicionador",),
    "Pasta dental": ("pasta dental", "crema dental"),
    "Enjuague bucal": ("enjuague bucal", "enjuague",),
    "Crema": ("crema corporal", "cremacorporal", "crema facial", "crema humectante"),
    "Loción": ("locion corporal", "loción corporal", "locion humectante"),
    "Bloqueador": ("bloqueador", "protector solar", "fotoprotector"),
    "Desodorante": ("desodorante", "antitranspirante"),
    "Repelente": ("repelente", "antimosquito", "antimosquitos", "repelente mosquito"),
    "Pañal": ("panal", "pañal", "panales", "pañales", "panal bebe", "pañal bebé"),
    "Toallita húmeda": ("toallita humeda", "toallita húmeda", "toallitas humedas", "toallitas húmedas", "toallita"),
    "Toalla higiénica": ("toalla higienica", "toalla higiénica", "toallas higienicas", "toallas higiénicas", "protector diario"),
    "Papel higiénico": ("papel higienico", "papel higiénico", "higienico"),
    "Papel toalla": ("papel toalla", "toalla cocina"),
    "Alcohol": ("alcohol", "alcohol medicinal", "alcohol etílico", "alcohol etilico"),
    "Agua oxigenada": ("agua oxigenada",),
    "Tableta": ("tableta", "tabletas", "pastilla", "pastillas", "comprimido", "comprimidos"),
    "Cápsula": ("capsula", "cápsula", "capsulas", "cápsulas"),
    "Jarabe": ("jarabe",),
    "Suplemento": ("suplemento", "multivitaminico", "multivitamínico", "vitamina", "vitaminas", "ashwagandha", "complemento"),
    "Antibiótico": ("antibiotico", "antibiótico", "amoxicilina", "azitromicina", "cefalexina"),
    "Analgésico": ("analgesico", "analgésico", "ibuprofeno", "paracetamol", "naproxeno", "diclofenaco"),
    "Antigripal": ("antigripal",),
    "Antiácido": ("antiacido", "antiácido"),
    "Sulfato Ferroso": ("sulfato ferroso", "sulfato",),
    "Simeticona": ("simeticona", "simet"),
    "Clopidogrel": ("clopidogrel", "clopidro"),
    "Loratadina": ("loratadina",),
    "Omeprazol": ("omeprazol",),
    "Metformina": ("metformina",),
    "Curitas": ("curitas", "curita", "venda adhesiva"),
}


BRAND_DEFAULT_PRODUCT_TYPES: dict[str, str] = {
    # Bebidas
    "Fanta": "Gaseosa",
    "Coca-Cola": "Gaseosa",
    "Inca Kola": "Gaseosa",
    "Sprite": "Gaseosa",
    "Pepsi": "Gaseosa",
    "Seven Up": "Gaseosa",
    "Kola Real": "Gaseosa",
    "Big Cola": "Gaseosa",
    "Guaraná": "Gaseosa",
    "San Luis": "Agua",
    "Cielo": "Agua",
    "San Mateo": "Agua",
    "San Carlos": "Agua",
    "Cifrut": "Jugo",
    "Pulp": "Jugo",
    "Frugos": "Jugo",
    "Tampico": "Jugo",
    "Sporade": "Bebida rehidratante",
    "Powerade": "Bebida rehidratante",
    "Gatorade": "Bebida rehidratante",
    "Aquarius": "Bebida rehidratante",
    "Volt": "Energizante",
    "Maltin Power": "Energizante",
    "Red Bull": "Energizante",
    "Monster": "Energizante",
    "Cuatro Gallos": "Pisco",
    "Tres Generaciones": "Pisco",
    # Abarrotes
    "Primor": "Aceite",
    "Cocinero": "Aceite",
    "Capri": "Aceite",
    "Crisol": "Aceite",
    "Sao": "Aceite",
    "Alacena": "Mayonesa",
    "Hellmann's": "Mayonesa",
    "Fanny": "Atún",
    "Real": "Atún",
    "Campomar": "Atún",
    "A-1": "Atún",
    "Quaker": "Avena",
    "Ángel": "Avena",
    "Maizena": "Fideos",
    "Bell's": "Azúcar",
    # Cuidado personal
    "Head & Shoulders": "Shampoo",
    "Pantene": "Shampoo",
    "Nivea": "Crema",
    "Sedal": "Shampoo",
    "Savital": "Shampoo",
    "Plusbelle": "Shampoo",
    "Konzil": "Shampoo",
    "Klorane": "Shampoo",
    "Dento": "Pasta dental",
    "Kolynos": "Pasta dental",
    "Colgate": "Pasta dental",
    "Sensodyne": "Pasta dental",
    "Oral-B": "Pasta dental",
    "Listerine": "Enjuague bucal",
    "Rexona": "Desodorante",
    "Old Spice": "Desodorante",
    "Speed Stick": "Desodorante",
    "Axe": "Desodorante",
    "Adidas": "Desodorante",
    "Asepxia": "Jabón",
    "Bioderma": "Crema",
    "Eucerin": "Crema",
    "Pond's": "Crema",
    "Cicatricure": "Crema",
    "Hipoglós": "Crema",
    "Bepanthene": "Crema",
    "Johnson's": "Shampoo",
    "Mustela": "Crema",
    "Babysec": "Pañal",
    "Huggies": "Pañal",
    "Pampers": "Pañal",
    "Bebito": "Pañal",
    "Always": "Toalla higiénica",
    "Kotex": "Toalla higiénica",
    "Nosotras": "Toalla higiénica",
    "Stayfree": "Toalla higiénica",
    "Ladysoft": "Toalla higiénica",
    "Elite": "Papel higiénico",
    "Suave": "Papel higiénico",
    "Noble": "Papel higiénico",
    "Paracas": "Papel higiénico",
    "Scott": "Papel toalla",
    "Familia": "Papel higiénico",
    # Limpieza
    "Ariel": "Detergente",
    "Opal": "Detergente",
    "Ace": "Detergente",
    "Skip": "Detergente",
    "Sapolio": "Lavavajilla",
    "Patito": "Lavavajilla",
    "Magistral": "Lavavajilla",
    "Vel Rosita": "Detergente",
    "Magia Blanca": "Detergente",
    "Marsella": "Jabón",
    "Bolívar": "Jabón",
    "Ayudín": "Lejía",
    "Clorox": "Lejía",
    "Domestos": "Lejía",
    "Lysol": "Ambientador",
    "Poett": "Ambientador",
    "Glade": "Ambientador",
    "Mr. Músculo": "Ambientador",
    "Fabuloso": "Ambientador",
    "Sapolio Cera": "Cera",
    # Farmacia
    "Panadol": "Tableta",
    "Aspirina": "Tableta",
    "Apronax": "Tableta",
    "Buscapina": "Tableta",
    "Mejoral": "Tableta",
    "Refrianex": "Jarabe",
    "Notuss": "Jarabe",
    "Sertal": "Tableta",
    "Doloflam": "Tableta",
    "Dolofrix": "Tableta",
    "Pepto-Bismol": "Jarabe",
    "Alka-Seltzer": "Tableta",
    "Sal de Andrews": "Suplemento",
    "Eno": "Suplemento",
    "Centrum": "Suplemento",
    "Redoxon": "Suplemento",
    "Pharmaton": "Suplemento",
    "Supradyn": "Suplemento",
    "Sunvit": "Suplemento",
    "Ashwagandha": "Suplemento",
    "Repel": "Repelente",
    "OFF!": "Repelente",
    "Himalaya": "Suplemento",
    "Vick": "Crema",
    "Mentholatum": "Crema",
    # Snacks
    "Picaras": "Galleta",
    "Cua Cua": "Galleta",
    "Soda Field": "Galleta",
    "Margaritas": "Galleta",
    "Glacitas": "Galleta",
    "Charada": "Galleta",
    "Vainilla Field": "Galleta",
    "Animalitos": "Galleta",
    "Doña Pepa": "Galleta",
    "Tentación": "Galleta",
    "Princesa": "Chocolate",
    "Sublime": "Chocolate",
    "Triángulo": "Chocolate",
    "Doritos": "Snack",
    "Cheese Tris": "Snack",
    "Piqueo Snax": "Snack",
    "Karinto": "Snack",
    "Pringles": "Snack",
    "Tortees": "Snack",
    "Lay's": "Snack",
    "Cuates": "Caramelo",
    "Ritz": "Galleta",
}


PRODUCT_TYPE_CATEGORIES: dict[str, str] = {
    "Gaseosa": "bebidas",
    "Agua": "bebidas",
    "Jugo": "bebidas",
    "Bebida rehidratante": "bebidas",
    "Energizante": "bebidas",
    "Pisco": "bebidas",
    "Cerveza": "bebidas",
    "Leche": "lacteos",
    "Yogurt": "lacteos",
    "Mantequilla": "lacteos",
    "Margarina": "lacteos",
    "Queso": "lacteos",
    "Arroz": "abarrotes",
    "Azúcar": "abarrotes",
    "Fideos": "abarrotes",
    "Aceite": "abarrotes",
    "Atún": "abarrotes",
    "Avena": "abarrotes",
    "Quinua": "abarrotes",
    "Kiwicha": "abarrotes",
    "Lentejas": "abarrotes",
    "Frijoles": "abarrotes",
    "Maní": "abarrotes",
    "Soya": "abarrotes",
    "Mayonesa": "abarrotes",
    "Ketchup": "abarrotes",
    "Mostaza": "abarrotes",
    "Galleta": "snacks y golosinas",
    "Chocolate": "snacks y golosinas",
    "Caramelo": "snacks y golosinas",
    "Snack": "snacks y golosinas",
    "Detergente": "limpieza",
    "Lejía": "limpieza",
    "Lavavajilla": "limpieza",
    "Jabón": "limpieza",
    "Cera": "limpieza",
    "Ambientador": "limpieza",
    "Shampoo": "cuidado personal",
    "Acondicionador": "cuidado personal",
    "Pasta dental": "cuidado personal",
    "Enjuague bucal": "cuidado personal",
    "Crema": "cuidado personal",
    "Loción": "cuidado personal",
    "Bloqueador": "cuidado personal",
    "Desodorante": "cuidado personal",
    "Papel higiénico": "cuidado personal",
    "Papel toalla": "cuidado personal",
    "Toalla higiénica": "cuidado personal",
    "Pañal": "bebés y mamá",
    "Toallita húmeda": "bebés y mamá",
    "Alcohol": "farmacia/otc",
    "Agua oxigenada": "farmacia/otc",
    "Tableta": "farmacia/otc",
    "Cápsula": "farmacia/otc",
    "Jarabe": "farmacia/otc",
    "Suplemento": "farmacia/otc",
    "Antibiótico": "farmacia/otc",
    "Analgésico": "farmacia/otc",
    "Antigripal": "farmacia/otc",
    "Antiácido": "farmacia/otc",
    "Sulfato Ferroso": "farmacia/otc",
    "Simeticona": "farmacia/otc",
    "Clopidogrel": "farmacia/otc",
    "Loratadina": "farmacia/otc",
    "Omeprazol": "farmacia/otc",
    "Metformina": "farmacia/otc",
    "Repelente": "farmacia/otc",
    "Curitas": "farmacia/otc",
}


UNIT_ALIASES: dict[str, str] = {
    "g": "g",
    "gr": "g",
    "grs": "g",
    "gramo": "g",
    "gramos": "g",
    "kg": "kg",
    "kgs": "kg",
    "kilo": "kg",
    "kilos": "kg",
    "kilogramo": "kg",
    "kilogramos": "kg",
    "mg": "mg",
    "miligramo": "mg",
    "miligramos": "mg",
    "ml": "ml",
    "m.l": "ml",
    "mililitro": "ml",
    "mililitros": "ml",
    "cc": "ml",
    "l": "L",
    "lt": "L",
    "lts": "L",
    "litro": "L",
    "litros": "L",
    "oz": "oz",
    "onza": "oz",
    "onzas": "oz",
    "unid": "unid",
    "unidad": "unid",
    "unidades": "unid",
    "und": "unid",
    "unds": "unid",
    "u": "unid",
    "pack": "pack",
    "caja": "caja",
    "cajas": "caja",
    "sobre": "sobre",
    "sobres": "sobre",
    "frasco": "frasco",
    "frascos": "frasco",
    "botella": "botella",
    "botellas": "botella",
    "sachet": "sachet",
    "sachets": "sachet",
    "tab": "tab",
    "tabs": "tab",
    "cap": "cap",
    "caps": "cap",
    "rollo": "rollo",
    "rollos": "rollo",
}


PRODUCT_STOPWORDS: set[str] = {
    "contenido",
    "neto",
    "peso",
    "registro",
    "sanitario",
    "ruc",
    "lote",
    "vence",
    "vencimiento",
    "fecha",
    "elaborado",
    "distribuido",
    "industria",
    "peruana",
    "peru",
    "perú",
    "nuevo",
    "gratis",
    "caffeine",
    "free",
    "alto",
    "exceso",
    "evitar",
    "octogono",
    "octógono",
    "100",
    "natural",
    "naturae",
    "floots",
    "ingredientes",
    "modo",
    "uso",
    "consumir",
    "preferentemente",
    "antes",
    "almacenar",
    "lugar",
    "fresco",
    "seco",
    "marca",
    "registrada",
    "consultar",
    "medico",
    "médico",
}


NOISE_PHRASES: tuple[str, ...] = (
    "caffeine free",
    "alto en azucar",
    "alto en azúcar",
    "alto en sodio",
    "alto en grasas",
    "alto en grasas saturadas",
    "evitar su consumo",
    "evitar consumo",
    "ministerio de salud",
    "ministerio de la produccion",
    "ministerio de la producción",
    "octogono",
    "consultar a su medico",
    "consulte a su medico",
    "manipular con cuidado",
    "no ingerir",
    "uso externo",
    "industria peruana",
)
